/**
 * Build-time generator: extracts CONDUCTOR_API_CONTRACT.md §10.5 verbatim
 * and emits a TypeScript constant at
 * `packages/dispatch-menubar/src/coarchitect/section-10-5.generated.ts`.
 *
 * Authority chain (per operator C3 ack on COARCH-T02 startup, 2026-04-29):
 *   - F2-Fix-B from MB-S01 ADR (`docs/adr/MB-S01-anthropic-sdk-validation.md`
 *     §F2): inject §10.5 verbatim into orchestrator context (NOT system
 *     prompt). This generator produces the constant that
 *     `src/orchestrator/build-context.ts` injects into Sonnet's context tier.
 *   - Pattern mirrors `system-prompt.generated.ts` per system-prompt.md
 *     §"Artifact location".
 *   - CONDUCTOR_API_CONTRACT.md §10.5 is the frozen authority for the
 *     9-question self-check block; this generator is the one-way
 *     contract→TS pipeline.
 *
 * Run:
 *   cd packages/dispatch-menubar
 *   pnpm exec tsx scripts/generate-section-10-5.ts
 *
 * Or via package.json script: `pnpm generate:section-10-5`
 *
 * Invariants:
 *   - Extracts exactly the §10.5 block (heading + body, stops at §10.6).
 *   - Halts with non-zero exit if the section markers are absent or the
 *     extracted body lacks all 9 numbered questions (anti-fabrication
 *     guard: prevents shipping an empty constant if the contract is
 *     restructured without updating this generator).
 *   - Generated file is overwritten on every run; stable across runs
 *     when source is unchanged (deterministic).
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..', '..');
const CONTRACT_PATH = resolve(REPO_ROOT, 'CONDUCTOR_API_CONTRACT.md');
const OUTPUT_PATH = resolve(
  __dirname,
  '..',
  'src',
  'coarchitect',
  'section-10-5.generated.ts',
);

const START_HEADING = '### §10.5 Self-check questions';
const STOP_HEADING = '### §10.6';
const REQUIRED_QUESTION_COUNT = 9;

function main(): number {
  const contract = readFileSync(CONTRACT_PATH, 'utf8');
  const startIdx = contract.indexOf(START_HEADING);
  if (startIdx === -1) {
    console.error(
      `HALT: ${START_HEADING} not found in ${CONTRACT_PATH}. ` +
        `Contract may have been restructured; update generator markers.`,
    );
    return 1;
  }
  const stopIdx = contract.indexOf(STOP_HEADING, startIdx);
  if (stopIdx === -1) {
    console.error(
      `HALT: ${STOP_HEADING} not found after §10.5 in ${CONTRACT_PATH}. ` +
        `Cannot bound section extraction.`,
    );
    return 1;
  }

  const section = contract.slice(startIdx, stopIdx).trimEnd();

  // Verify all 9 numbered questions present (anti-fabrication guard).
  const questionCount = (section.match(/^\d+\. /gm) || []).length;
  if (questionCount !== REQUIRED_QUESTION_COUNT) {
    console.error(
      `HALT: extracted §10.5 contains ${questionCount} numbered questions; ` +
        `expected ${REQUIRED_QUESTION_COUNT}. Generator markers may have ` +
        `drifted from contract structure.`,
    );
    return 1;
  }

  const output = renderTypeScriptConstant(section);
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, output, 'utf8');

  console.log(
    `wrote ${OUTPUT_PATH} ` +
      `(${section.length} chars from CONDUCTOR_API_CONTRACT.md §10.5, ` +
      `${questionCount} questions verified)`,
  );
  return 0;
}

function renderTypeScriptConstant(section: string): string {
  // Use a JSON-encoded string literal so any special characters
  // (backticks, ${}, etc.) round-trip cleanly. Future-proofing in case
  // §10.5 is amended to include code samples or template syntax.
  const literal = JSON.stringify(section);
  return `// AUTOGENERATED — DO NOT EDIT BY HAND.
//
// Source: CONDUCTOR_API_CONTRACT.md §10.5 (frozen at 3ddca60, plus any
// subsequent contract amendments tracked there). Generator:
// \`packages/dispatch-menubar/scripts/generate-section-10-5.ts\`.
//
// Per F2-Fix-B from MB-S01 ADR (docs/adr/MB-S01-anthropic-sdk-validation.md
// §F2): \`SECTION_10_5_VERBATIM\` is injected verbatim into the
// orchestrator's context tier (NOT into the system prompt) so Sonnet 4.6
// can reproduce the exact 9 questions in \`draft-commit-message\` payloads.
// Operator-acked Path B per COARCH-T02 startup, 2026-04-29.
//
// To regenerate after a contract amendment:
//   cd packages/dispatch-menubar
//   pnpm exec tsx scripts/generate-section-10-5.ts

export const SECTION_10_5_VERBATIM: string = ${literal};
`;
}

process.exit(main());
