// Realistic-looking tmux content generators.
// Each agent type emits a stream of lines that look like real terminal output.

const AGENT_TEMPLATES = {
  frontend: {
    cmd: "pnpm dev",
    lines: [
      { t: 'sys', s: '$ pnpm dev' },
      { t: 'sys', s: '> conductor-ui@0.1.0 dev /workspace/apps/web' },
      { t: 'sys', s: '> next dev --turbo' },
      { t: 'sys', s: '' },
      { t: 'ok',  s: '  ▲ Next.js 15.0.3 (turbo)' },
      { t: 'sys', s: '  - Local:        http://localhost:3000' },
      { t: 'sys', s: '  - Environments: .env.local' },
      { t: 'sys', s: '' },
      { t: 'sys', s: ' ✓ Ready in 1.8s' },
      { t: 'sys', s: ' ○ Compiling /dashboard ...' },
      { t: 'ok',  s: ' ✓ Compiled /dashboard in 412ms (1284 modules)' },
      { t: 'sys', s: ' GET /dashboard 200 in 524ms' },
      { t: 'sys', s: ' ○ Compiling /api/runs ...' },
      { t: 'ok',  s: ' ✓ Compiled in 188ms (84 modules)' },
      { t: 'sys', s: ' GET /api/runs 200 in 91ms' },
      { t: 'warn',s: ' ⚠ Fast Refresh had to perform a full reload' },
      { t: 'sys', s: ' ○ Compiling /dashboard/[id] ...' },
      { t: 'ok',  s: ' ✓ Compiled in 244ms' },
    ],
  },
  api: {
    cmd: "cargo watch -x test",
    lines: [
      { t: 'sys', s: '$ cargo watch -x test' },
      { t: 'sys', s: '[Running: cargo test]' },
      { t: 'sys', s: '   Compiling conductor-api v0.3.1' },
      { t: 'sys', s: '   Compiling tower-http v0.6.2' },
      { t: 'sys', s: '    Finished test [unoptimized] in 14.21s' },
      { t: 'sys', s: '     Running unittests src/lib.rs' },
      { t: 'sys', s: '' },
      { t: 'sys', s: 'running 47 tests' },
      { t: 'ok',  s: 'test routes::runs::create_run ... ok' },
      { t: 'ok',  s: 'test routes::runs::list_runs ... ok' },
      { t: 'ok',  s: 'test routes::runs::cancel_run ... ok' },
      { t: 'ok',  s: 'test dispatch::queue::round_robin ... ok' },
      { t: 'ok',  s: 'test dispatch::queue::priority ... ok' },
      { t: 'ok',  s: 'test agents::tmux::attach_detach ... ok' },
      { t: 'ok',  s: 'test agents::tmux::capture_pane ... ok' },
      { t: 'ok',  s: 'test build_md::parser::sections ... ok' },
      { t: 'err', s: 'test build_md::parser::nested_blocks ... FAILED' },
      { t: 'sys', s: '' },
      { t: 'err', s: 'failures:' },
      { t: 'sys', s: '    build_md::parser::nested_blocks' },
    ],
  },
  db: {
    cmd: "sqlx migrate run",
    lines: [
      { t: 'sys', s: '$ sqlx migrate run' },
      { t: 'sys', s: 'Applied 20260514_init_schema (12.4ms)' },
      { t: 'sys', s: 'Applied 20260514_runs_table (8.1ms)' },
      { t: 'sys', s: 'Applied 20260515_agents_table (6.7ms)' },
      { t: 'sys', s: 'Applied 20260516_dispatch_log (9.3ms)' },
      { t: 'ok',  s: 'Database is up to date.' },
      { t: 'sys', s: '' },
      { t: 'sys', s: '$ psql -d conductor -c "select count(*) from runs;"' },
      { t: 'sys', s: ' count ' },
      { t: 'sys', s: '-------' },
      { t: 'sys', s: '   142' },
      { t: 'sys', s: '(1 row)' },
      { t: 'sys', s: '' },
      { t: 'sys', s: '$ pg_dump --schema-only > schema.sql' },
      { t: 'ok',  s: 'schema.sql written (4.2 KB)' },
    ],
  },
  deploy: {
    cmd: "fly deploy --remote-only",
    lines: [
      { t: 'sys', s: '$ fly deploy --remote-only' },
      { t: 'sys', s: '==> Verifying app config' },
      { t: 'ok',  s: '--> Verified app config' },
      { t: 'sys', s: '==> Building image with Depot' },
      { t: 'sys', s: '--> build:  digest: sha256:8af3b…  size: 184MB' },
      { t: 'sys', s: '--> push:   docker.io/conductor/api:edge' },
      { t: 'sys', s: 'WARN The app is not listening on the expected addr' },
      { t: 'sys', s: '--> Starting machine 6e82d199a39487' },
      { t: 'ok',  s: '--> Machine 6e82d199a39487 [app] update succeeded' },
      { t: 'sys', s: '--> Starting machine 9f0a443ce05738' },
      { t: 'ok',  s: '--> Machine 9f0a443ce05738 [app] update succeeded' },
      { t: 'ok',  s: ' ✓ deployed in 47s' },
    ],
  },
  test: {
    cmd: "vitest run --coverage",
    lines: [
      { t: 'sys', s: '$ vitest run --coverage' },
      { t: 'sys', s: ' DEV  v1.6.0  /workspace/packages/core' },
      { t: 'sys', s: '' },
      { t: 'ok',  s: ' ✓ src/parser.test.ts (12)' },
      { t: 'ok',  s: ' ✓ src/dispatch.test.ts (8)' },
      { t: 'ok',  s: ' ✓ src/queue.test.ts (6)' },
      { t: 'ok',  s: ' ✓ src/tmux/session.test.ts (14)' },
      { t: 'ok',  s: ' ✓ src/tmux/capture.test.ts (4)' },
      { t: 'sys', s: '' },
      { t: 'sys', s: ' Test Files  5 passed (5)' },
      { t: 'sys', s: '      Tests  44 passed (44)' },
      { t: 'sys', s: '   Duration  3.41s' },
      { t: 'sys', s: '' },
      { t: 'sys', s: ' % Coverage report from v8' },
      { t: 'sys', s: ' Statements   : 92.4% (1812/1961)' },
      { t: 'sys', s: ' Branches     : 87.1% (412/473)' },
      { t: 'sys', s: ' Functions    : 94.0% (188/200)' },
      { t: 'ok',  s: ' Lines        : 92.6% (1789/1932)' },
    ],
  },
  lint: {
    cmd: "biome check --apply .",
    lines: [
      { t: 'sys', s: '$ biome check --apply .' },
      { t: 'sys', s: 'Checked 318 files in 412ms' },
      { t: 'warn',s: 'lint/correctness/noUnusedVariables ─ src/agents/spawn.ts:42:7' },
      { t: 'warn',s: 'lint/style/useNamingConvention ─ src/api/runs.ts:18:13' },
      { t: 'sys', s: '' },
      { t: 'ok',  s: 'Applied 12 fixes across 7 files' },
      { t: 'sys', s: '$ git diff --stat' },
      { t: 'sys', s: ' src/agents/spawn.ts | 3 +--' },
      { t: 'sys', s: ' src/api/runs.ts    | 5 ++---' },
      { t: 'sys', s: ' src/dispatch.ts    | 2 +-' },
      { t: 'sys', s: ' 7 files changed, 9 insertions(+), 12 deletions(-)' },
    ],
  },
  worker: {
    cmd: "node workers/embed.js",
    lines: [
      { t: 'sys', s: '$ node workers/embed.js' },
      { t: 'sys', s: '[worker] booting embed worker pid=84221' },
      { t: 'sys', s: '[worker] connected to redis://localhost:6379' },
      { t: 'sys', s: '[worker] subscribed to queue: embed-jobs' },
      { t: 'sys', s: '[worker] processing job 9a4f… (842 chunks)' },
      { t: 'sys', s: '[worker]   ↳ batched 32, latency 184ms' },
      { t: 'sys', s: '[worker]   ↳ batched 64, latency 312ms' },
      { t: 'sys', s: '[worker]   ↳ batched 128, latency 612ms' },
      { t: 'ok',  s: '[worker] job 9a4f completed in 4.8s' },
      { t: 'sys', s: '[worker] processing job 17b2… (218 chunks)' },
      { t: 'sys', s: '[worker]   ↳ batched 32, latency 174ms' },
      { t: 'ok',  s: '[worker] job 17b2 completed in 1.2s' },
    ],
  },
  docs: {
    cmd: "mkdocs serve",
    lines: [
      { t: 'sys', s: '$ mkdocs serve' },
      { t: 'sys', s: 'INFO     -  Building documentation' },
      { t: 'sys', s: 'INFO     -  Cleaning site directory' },
      { t: 'sys', s: 'INFO     -  Documentation built in 1.42 seconds' },
      { t: 'sys', s: 'INFO     -  [10:24:11] Watching paths for changes' },
      { t: 'sys', s: 'INFO     -  [10:24:11] Serving on http://127.0.0.1:8000/' },
      { t: 'sys', s: 'INFO     -  [10:24:42] Detected file changes' },
      { t: 'sys', s: 'INFO     -  Building documentation' },
      { t: 'ok',  s: 'INFO     -  Documentation built in 0.88 seconds' },
    ],
  },
};

// The orchestrator's own pane: aggregated coordination log.
const ORCH_BANNER = [
  { t: 'banner', s: '  ┌─ conductor orchestrator ──────────────────────────────────' },
  { t: 'banner', s: '  │  build.md      auth-rewrite.build.md' },
  { t: 'banner', s: '  │  total steps   14    queued 3    running 4    done 7' },
  { t: 'banner', s: '  │  budget        $4.21 / $10.00     wall clock  06:42' },
  { t: 'banner', s: '  └────────────────────────────────────────────────────────────' },
  { t: 'sys', s: '' },
];

window.AGENT_TEMPLATES = AGENT_TEMPLATES;
window.ORCH_BANNER = ORCH_BANNER;
